# Generated by Django 4.2.25 on 2026-01-28 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parts', models.CharField(max_length=20, verbose_name='部位')),
                ('content', models.CharField(max_length=100, verbose_name='種目')),
                ('weight', models.CharField(max_length=10, verbose_name='重量')),
                ('rep', models.CharField(max_length=10, verbose_name='回数')),
                ('memo', models.TextField(null=True, verbose_name='メモ')),
                ('posted_at', models.DateField(auto_now_add=True, verbose_name='投稿日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(blank=True, default=0)),
                ('rep', models.IntegerField(blank=True, default=0)),
                ('memo', models.TextField(blank=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.menuitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
