# Generated by Django 4.2.26 on 2025-11-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='日付')),
                ('parts', models.CharField(max_length=10, verbose_name='部位')),
                ('content', models.TextField(verbose_name='種目')),
                ('weight', models.CharField(max_length=10, verbose_name='重量')),
                ('rep', models.CharField(max_length=10, verbose_name='回数')),
                ('memo', models.TextField(verbose_name='メモ')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='種目'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parts',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='部位'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='rep',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='回数'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='weight',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='重量'),
        ),
    ]
