# Generated by Django 4.2.25 on 2026-01-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='rep',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.CharField(blank=True, default=0, max_length=10),
        ),
    ]
