# Generated by Django 4.2.26 on 2025-11-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_record_remove_menuitem_comment_remove_menuitem_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='content',
            field=models.CharField(default='未設定', max_length=100, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parts',
            field=models.CharField(default='未設定', max_length=20, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='rep',
            field=models.CharField(default='未設定', max_length=10, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='weight',
            field=models.CharField(default='未設定', max_length=10, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.CharField(default='未設定', max_length=10, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='record',
            name='parts',
            field=models.CharField(default='未設定', max_length=10, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rep',
            field=models.CharField(default='未設定', max_length=10, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.CharField(default='未設定', max_length=10, verbose_name='重量'),
        ),
    ]
