# Generated by Django 4.2.25 on 2026-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_alter_record_rep_alter_record_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='rep',
            field=models.IntegerField(max_length=10, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='weight',
            field=models.IntegerField(max_length=10, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rep',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
