# Generated by Django 4.2.26 on 2025-11-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_menuitem_content_alter_menuitem_parts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='content',
            field=models.CharField(max_length=100, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parts',
            field=models.CharField(max_length=20, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='rep',
            field=models.CharField(max_length=10, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='weight',
            field=models.CharField(max_length=10, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.CharField(max_length=10, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='record',
            name='parts',
            field=models.CharField(max_length=10, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rep',
            field=models.CharField(max_length=10, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.CharField(max_length=10, verbose_name='重量'),
        ),
    ]
