# Generated by Django 4.2.26 on 2025-11-21 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0004_alter_menuitem_content_alter_menuitem_parts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='post',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content',
            field=models.CharField(max_length=100, null=True, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='memo',
            field=models.TextField(null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parts',
            field=models.CharField(max_length=20, null=True, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='rep',
            field=models.CharField(max_length=10, null=True, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='weight',
            field=models.CharField(max_length=10, null=True, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.CharField(max_length=10, null=True, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='record',
            name='parts',
            field=models.CharField(max_length=10, null=True, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='record',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rep',
            field=models.CharField(max_length=10, null=True, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.CharField(max_length=10, null=True, verbose_name='重量'),
        ),
        migrations.DeleteModel(
            name='MenuPost',
        ),
    ]
