# Generated by Django 4.2.26 on 2025-11-21 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_record_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='posted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
