# Generated by Django 4.2.26 on 2025-11-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_record_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='日付'),
        ),
    ]
