# Generated by Django 4.2.26 on 2025-11-21 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0008_alter_record_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿日時'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.CharField(max_length=100, null=True, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='record',
            name='parts',
            field=models.CharField(max_length=20, null=True, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='record',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='投稿日時'),
        ),
    ]
