# Generated by Django 4.2.26 on 2025-11-21 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0009_record_user_alter_menuitem_posted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='day',
            field=models.CharField(default='', max_length=20, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='content',
            field=models.CharField(default='', max_length=100, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='memo',
            field=models.TextField(default='', null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parts',
            field=models.CharField(default='', max_length=20, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='rep',
            field=models.CharField(default='', max_length=10, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='weight',
            field=models.CharField(default='', max_length=10, verbose_name='重量'),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.CharField(default='', max_length=100, verbose_name='種目'),
        ),
        migrations.AlterField(
            model_name='record',
            name='memo',
            field=models.TextField(default='', null=True, verbose_name='メモ'),
        ),
        migrations.AlterField(
            model_name='record',
            name='parts',
            field=models.CharField(default='', max_length=20, verbose_name='部位'),
        ),
        migrations.AlterField(
            model_name='record',
            name='rep',
            field=models.CharField(default='', max_length=10, verbose_name='回数'),
        ),
        migrations.AlterField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ'),
        ),
        migrations.AlterField(
            model_name='record',
            name='weight',
            field=models.CharField(default='', max_length=10, verbose_name='重量'),
        ),
    ]
